#
## 数据源配置
#spring:
#  datasource:
#    druid:
#      # 主库数据源
#      bop92:
#        enabled: true
#        url: jdbc:oracle:thin:@10.20.23.117:1521:orcl
#        username: hs_user
#        password: hundsun
#        driverClassName: oracle.jdbc.driver.OracleDriver
#      # 主库数据源
#      bop102:
#        enabled: false
#        url: jdbc:oracle:thin:@10.20.23.117:1521:orcl
#        username: root
#        password: root
#        driverClassName: oracle.jdbc.driver.OracleDriver
#      # 我的阿里云
#      aliyun:
#        #从数据源开关/默认关闭
#        enabled: false
#        url: jdbc:mysql://150.158.192.63:3306/feiyu?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#        username: feiyu
#        password: feiyu
#        driverClassName: com.mysql.cj.jdbc.Driver
#        type: com.alibaba.druid.pool.DruidDataSource
#      # 初始连接数
#      initialSize: 5
#      # 最小连接池数量
#      minIdle: 10
#      # 最大连接池数量
#      maxActive: 20
#      # 配置获取连接等待超时的时间
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      # 配置一个连接在池中最大生存的时间，单位是毫秒
#      maxEvictableIdleTimeMillis: 900000
#      # 配置检测连接是否有效
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      webStatFilter:
#        enabled: true
#      filter:
#        stat:
#          enabled: true
#          # 慢SQL记录
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: true
#        wall:
#          config:
#            multi-statement-allow: true
#
